// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-news-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { z } from "npm:zod@^4.4.3";
var list_news_posts_default = defineTool({
  name: "list_news_posts",
  title: "List news posts",
  description: "List published news/blog posts from Relanova (title, slug, excerpt, category, published date).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max posts to return (default 10)."),
    category: z.string().optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("blog_posts").select("slug,title,excerpt,category,tags,author,published_at,cover_image_url").eq("published", true).order("published_at", { ascending: false }).limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-news-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.3";
import { z as z2 } from "npm:zod@^4.4.3";
var get_news_post_default = defineTool2({
  name: "get_news_post",
  title: "Get news post",
  description: "Fetch a single published news/blog post from Relanova by slug, including full content.",
  inputSchema: {
    slug: z2.string().min(1).describe("The post slug (from list_news_posts).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("blog_posts").select("slug,title,excerpt,content,category,tags,author,published_at,cover_image_url,seo_title,seo_description").eq("published", true).eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No published post with slug "${slug}".` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/get-company-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var INFO = {
  name: "Relanova",
  founder: "Monia Ben Tahar",
  role: "Ecosystem Architect",
  location: "Sint-Baafs-Vijve, Belgi\xEB",
  email: "monia@mbtconsult.be",
  phone: "+32 488 285 886",
  website: "https://relanova.be",
  languages: ["Nederlands (NL-BE)", "Engels", "Frans"],
  focus: "Strategisch consulting voor KMO's en scale-ups: strategie, business development, marketing, communicatie en partnerships.",
  methodology: {
    name: "BRIDGE",
    tagline: "6-layer strategic framework",
    layers: [
      { letter: "B", title: "Business Focus", description: "Strategie & ambitie" },
      { letter: "R", title: "Relevantie & Realiteit", description: "Marktanalyse" },
      { letter: "I", title: "Identiteit & Inzicht", description: "Positionering" },
      { letter: "D", title: "Design & Richting", description: "Strategische planning" },
      { letter: "G", title: "Groei & Partnerships", description: "Business development" },
      { letter: "E", title: "Expansie & Evaluatie", description: "Schaalbaar maken" }
    ]
  }
};
var get_company_info_default = defineTool3({
  name: "get_company_info",
  title: "Get Relanova info",
  description: "Returns public information about Relanova: contact, focus, and the BRIDGE methodology.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(INFO, null, 2) }],
    structuredContent: INFO
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "relanova-mcp",
  title: "Relanova MCP",
  version: "0.1.0",
  instructions: "Public tools for the Relanova consulting website. Use `get_company_info` for contact, focus and the BRIDGE methodology; `list_news_posts` to browse published news/blog posts; `get_news_post` to read a single post by slug.",
  tools: [get_company_info_default, list_news_posts_default, get_news_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
